vich_uploader:
    db_driver: orm

    mappings:
        films:
            uri_prefix: /images/films
            upload_destination: '%kernel.project_dir%/public/images/films'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
